### ISSUE TITLE
AttributeError: 'IALUT_LLVE' object has no attribute 'backbone_name'

### ISSUE THREAD

**Issue by Liampour** [Wenhao-Li-777/FastLLVE#6]
Hello,
congratulations for your work!!
When I execute `python quantitative_test.py -opt options/test/test_in_sdsd.yml` to test an image the following error appears:

```
Traceback (most recent call last):
  File "quantitative_test.py", line 96, in <module>
    main()
  File "quantitative_test.py", line 22, in main
    model = create_model(opt)
  File "/home/username/FastLLVE/models/__init__.py", line 11, in create_model
    m = M(conf)
  File "/home/username/FastLLVE/models/Video_model.py", line 28, in __init__
    self.netG = networks.define_G(conf).to(self.device)
  File "/home/username/FastLLVE/models/networks.py", line 19, in define_G
    netG = enhance_model.IALUT_LLVE(input_resolution=conf_net['input_resolution'],
  File "/home/username/FastLLVE/models/IALUT/IALUT_model.py", line 41, in __init__
    self.init_weights()
  File "/home/username/FastLLVE/models/IALUT/IALUT_model.py", line 51, in init_weights
    if self.backbone_name not in ['res18']:
  File "/home/username/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'IALUT_LLVE' object has no attribute 'backbone_name'
```

Any suggestions?

**Comment by ShaochengShen** [comment]
same question
